### ISSUE TITLE
ubuntu下运行失败

### ISSUE THREAD

**Issue by lxsyz** [litten/zing-gallery#16]
npm i会有warning: file-loader@1.1.6 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself,但是我的webpack可以使用额，版本是1.15.0
之后npm run start报错
zing-gallery listening on localhost:3000
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/program/zing-gallery/node_modules/webp-bin/vendor/linux/cwebp ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
不知所措

**Comment by ohblue** [comment]
跟你一样

**Comment by atompi** [comment]
@lxsyz @ohblue Ubuntu 环境先 `apt` 安装 `gcc-multilib` ：

```
sudo apt-get install -y gcc-multilib
```

然后再 `npm install`

**Comment by lxsyz** [comment]
@mission802 多谢，可以了

**Comment by ihewro** [comment]
我也这样，不过是mac，怎么解决呢？
