### ISSUE TITLE
需要的Node 和 Npm 版本是多少？

### ISSUE THREAD

**Issue by snksos** [litten/zing-gallery#4]
之前踩了坑，ubuntu默认安装的 Node Npm版本很低，导致直接运行不起来，自己手动又升级的，但还是有 问题：就是之前别人踩的坑，新增的相册，点不进去
所以，求告知 需要的 Node Npm 版本多少？

**Comment by DXnima** [comment]
运行成功了吗，用的哪个版本，npm i 我一直报错：

```
Error: Cannot find module '/root/zing-gallery/node_modules/images/scripts/nothing.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN url-loader@0.5.9 requires a peer of file-loader@* but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! images@3.2.4 install: `node scripts/nothing.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the images@3.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-15T06_59_59_159Z-debug.log
```
